### PR TITLE
Commiting AnjanClass2 to BranchX

### PR DESCRIPTION
**Pull request by AnjiDirisala**
Hi Ramya,

I have committed AnjanClass2. So please review AND APPROVE.

Thank You 
AD

### CODE REVIEW

**Comment by SreeNallamothu** [comment]
Hi Anjan,

Your code looks good. Add one more sysout.

Thank You 
Ramya

**Comment by AnjiDirisala** [comment]
Hi Ramya,

I have added extra sysout. Please check it.

Thank you
AD

**Comment by SreeNallamothu** [comment]
Hi Anjan,

You can merge to master branch.

**Comment by SreeNallamothu** [comment]
Yenti ra edi😂😂

**Comment by AnjiDirisala** [comment]
😂😂

**Pull request merged**
